### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by phaax**
**Changed**: Use save state slot 1 instead of filename.
**Changed**: Hardcoded memory locations are now stored in SMW.lua ("borrowed" from https://github.com/rodamaral/smw-tas)
**Added**: Sprite detection and lookup table (sprites.lua) for simple configuration (deadly = true/false).
**Fixed**??: Level tile cache - variable level sizes. Vertical levels needs testing.

**Note**: Doesn't work for large enemies (ex. Banzai Bill). Do we need to read SMW.WRAM.sprite_memory_header to fix this?

### CODE REVIEW

**Comment by meepen** [comment]
You're going ham on this, you should inform me when you are done making changes and I should pull this. Alternatively since you seem to be making a lot of progress you could maintain your own fork.

**Comment by phaax** [comment]
You can pull this, I'm done making changes. :) I can't do much more right now anyway and everything seems to work very well. You figured out how to get the Banzai Bill detected earlier so that's one improvement that really needs to find it's way back into ram.getSprites(), I hope you have any ideas there.

I haven't done anything in Lua before so I hope you are happy with my code. :D

**Comment by meepen** [comment]
All looks fine with this - I'm assuming you tested this thoroughly. Nice job!

**Comment by phaax** [comment]
Thanks :)
Yeah, It's working properly now as far as I can tell. I've been running it for 72 hours or so!

**Pull request merged**
